version: '3'
services:
  golgi:
    container_name: golgi
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 3004:3004
      - 3005:3005
      - 3006:3006
      - 3007:3007
    volumes:
      - golgi-data:/app/data
volumes:
  golgi-data:
    driver: local
    driver_opts:
      type: none
      device: /data
      o: bind
